# Generated by Django 4.1.4 on 2022-12-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
