# Generated by Django 4.1.5 on 2023-01-07 16:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='core/images', validators=[core.validators.validate_image_size]),
        ),
    ]
