# Generated by Django 4.1.7 on 2023-04-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tryprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryProfile',
        ),
    ]
