# Generated by Django 4.1.5 on 2023-03-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_likeditem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DislikedItem',
        ),
    ]
