# Generated by Django 4.1.5 on 2023-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_delete_dislikeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
