# Generated by Django 4.1.5 on 2023-03-19 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0006_likeditem_is_liked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedItem',
            new_name='Reaction',
        ),
    ]
