# Generated by Django 4.1.7 on 2023-04-01 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0007_rename_likeditem_reaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='Like',
        ),
    ]
