# Generated by Django 4.1.7 on 2023-04-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0009_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(choices=[(8, 'Article'), (9, 'Issue')], on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
