# Generated by Django 4.1.7 on 2023-04-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0028_alter_like_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
