# Generated by Django 4.1.7 on 2023-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0033_alter_like_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
