# Generated by Django 4.1.7 on 2023-04-23 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0034_alter_comment_message_alter_reply_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Invalid characters. Only alphanumeric and punctuation characters are allowed.', regex='^[A-Za-z0-9 _.,!?:@#%&()*+=;/\\-]+$'), django.core.validators.RegexValidator(message='Invalid characters. Only ASCII characters are allowed.', regex='[^\x00-\x7f]+'), django.core.validators.RegexValidator(message='Invalid characters. Only non-space characters are allowed.', regex='[^\\s]+'), django.core.validators.RegexValidator(message='Invalid characters. Only alphanumeric and punctuation characters, as well as the 👍 and 👎 emojis, are allowed.', regex='^[\\w\\d\\s.,!?:@#%&()*+=;/\\-👍👎]+$')]),
        ),
    ]
