# Generated by Django 4.1.4 on 2022-12-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member'),
        ),
        migrations.AlterField(
            model_name='article',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member'),
        ),
        migrations.AlterField(
            model_name='memberposition',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member'),
        ),
    ]
