# Generated by Django 4.1.4 on 2022-12-27 18:27

from django.db import migrations, models
import django.db.models.deletion
import publication.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='publication/images', validators=[publication.validators.validate_image_size]),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publication/banners', validators=[publication.validators.validate_image_size])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member')),
            ],
        ),
    ]
