# Generated by Django 4.1.4 on 2022-12-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_alter_articleimage_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
