# Generated by Django 4.1.4 on 2022-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_announcement_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('LF', 'Literary Folio'), ('T', 'Tabloid'), ('SM', 'Sports Magazine'), ('N', 'Newsletter')], max_length=2),
        ),
    ]
