# Generated by Django 4.1.5 on 2023-01-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_articlepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlePermission',
        ),
    ]
