# Generated by Django 4.1.5 on 2023-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0011_delete_articlepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
