# Generated by Django 4.1.5 on 2023-01-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_alter_article_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_enabled',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_enabled',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
