# Generated by Django 4.1.5 on 2023-01-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0013_alter_article_is_enabled_alter_issue_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('approve_article', 'Can approve article'), ('disapprove_article', 'Can disapprove article'), ('enable_article', 'Can enable article'), ('disable_article', 'Can disable article')]},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('approve_issue', 'Can approve issue'), ('disapprove_issue', 'Can disapprove issue'), ('enable_issue', 'Can enable issue'), ('disable_issue', 'Can disable issue')]},
        ),
    ]
