# Generated by Django 4.1.5 on 2023-01-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0015_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
