# Generated by Django 4.1.5 on 2023-01-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0017_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('approve', 'Can approve issue'), ('disapprove', 'Can disapprove issue'), ('enable', 'Can enable issue'), ('disable', 'Can disable issue')]},
        ),
    ]
