# Generated by Django 4.1.5 on 2023-01-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0018_alter_issue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('disapprove', 'Can disapprove article'), ('enable', 'Can enable article'), ('disable', 'Can disable article')]},
        ),
    ]
