# Generated by Django 4.1.5 on 2023-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0021_alter_issue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
