# Generated by Django 4.1.5 on 2023-01-09 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0023_alter_article_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberposition',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
