# Generated by Django 4.1.5 on 2023-01-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0024_memberposition_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberposition',
            name='datetime',
        ),
    ]
