# Generated by Django 4.1.5 on 2023-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0025_remove_memberposition_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
