# Generated by Django 4.1.5 on 2023-01-23 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0026_alter_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='volume_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
