# Generated by Django 4.1.5 on 2023-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0027_alter_issue_issue_number_alter_issue_volume_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
