# Generated by Django 4.1.5 on 2023-01-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0031_banner_try_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='try_lng',
        ),
    ]
