# Generated by Django 4.1.5 on 2023-03-18 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0033_rename_is_approved_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='duration',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(2), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
