# Generated by Django 4.1.5 on 2023-03-18 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0034_article_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='duration',
        ),
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
