# Generated by Django 4.1.5 on 2023-03-19 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0037_alter_article_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
