# Generated by Django 4.1.5 on 2023-03-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0038_issue_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='is_approved',
            new_name='is_published',
        ),
    ]
