# Generated by Django 4.1.5 on 2023-03-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0040_article_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='member',
            new_name='author',
        ),
    ]
