# Generated by Django 4.1.5 on 2023-03-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0041_rename_member_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.article')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member')),
            ],
        ),
    ]
