# Generated by Django 4.1.5 on 2023-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0043_delete_articlecollaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_collaborators', to='publication.article')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member')),
            ],
        ),
    ]
