# Generated by Django 4.1.5 on 2023-03-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0044_articlecollaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecollaborator',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.member', unique=True),
        ),
    ]
