# Generated by Django 4.1.5 on 2023-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0045_alter_articlecollaborator_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='publication.member', verbose_name='authors'),
        ),
    ]
