# Generated by Django 4.1.5 on 2023-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0046_remove_article_author_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCollaborator',
        ),
    ]
