# Generated by Django 4.1.5 on 2023-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0047_delete_articlecollaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='publication.member'),
        ),
    ]
