# Generated by Django 4.1.5 on 2023-03-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0048_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='publication.member'),
        ),
    ]
