# Generated by Django 4.1.5 on 2023-03-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0050_remove_article_author_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='publication.member'),
        ),
    ]
