# Generated by Django 4.1.5 on 2023-03-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0051_remove_article_author_article_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='publication.member'),
        ),
    ]
