# Generated by Django 4.1.5 on 2023-03-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0052_alter_article_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authors',
            new_name='author',
        ),
    ]
