# Generated by Django 4.1.5 on 2023-03-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0055_authorarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
