# Generated by Django 4.1.5 on 2023-03-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0056_remove_article_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorArticle',
            new_name='ArticleAuthor',
        ),
    ]
