# Generated by Django 4.1.5 on 2023-03-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0057_rename_authorarticle_articleauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='publication.article'),
            preserve_default=False,
        ),
    ]
