# Generated by Django 4.1.5 on 2023-03-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0058_alter_articleauthor_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorposition',
            old_name='member',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='member',
            new_name='author',
        ),
    ]
