# Generated by Django 4.1.7 on 2023-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0059_rename_member_authorposition_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.author', unique=True),
        ),
    ]
