# Generated by Django 4.1.7 on 2023-03-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0061_alter_articleauthor_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publication.author'),
        ),
    ]
