# Generated by Django 4.1.7 on 2023-03-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0064_remove_issue_author_issue_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
    ]
