# Generated by Django 4.1.7 on 2023-03-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0065_remove_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ManyToManyField(to='publication.author'),
        ),
    ]
