# Generated by Django 4.1.7 on 2023-03-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0067_remove_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publication.author'),
            preserve_default=False,
        ),
    ]
