# Generated by Django 4.1.7 on 2023-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0068_issue_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sample_authors',
            field=models.ManyToManyField(related_name='articles', to='publication.author'),
        ),
    ]
