# Generated by Django 4.1.7 on 2023-03-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0069_article_sample_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
