# Generated by Django 4.1.7 on 2023-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0071_rename_sample_authors_article_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_pen_name', models.CharField(max_length=255)),
            ],
        ),
    ]
