# Generated by Django 4.1.7 on 2023-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0073_article_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='publication.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, to='publication.contributor'),
        ),
    ]
