# Generated by Django 4.1.7 on 2023-04-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0076_remove_article_is_enabled_remove_article_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
