# Generated by Django 4.1.7 on 2023-04-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0077_article_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contributors',
        ),
        migrations.AddField(
            model_name='contributor',
            name='article',
            field=models.ManyToManyField(to='publication.article'),
        ),
    ]
