# Generated by Django 4.1.7 on 2023-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0078_remove_article_contributors_contributor_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='contributors',
            field=models.ManyToManyField(to='publication.contributor'),
        ),
    ]
