# Generated by Django 4.1.7 on 2023-04-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0079_remove_contributor_article_article_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('NF', 'News Feature'), ('F', 'Feature'), ('O', 'Opinion'), ('C', 'Culture'), ('E', 'Editorial'), ('CT', 'Caption Type')], max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_or_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
