# Generated by Django 4.1.7 on 2023-04-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0086_alter_reader_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={},
        ),
    ]
