# Generated by Django 4.1.7 on 2023-04-01 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0087_alter_reader_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='city',
            field=models.CharField(default='+', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reader',
            name='country',
            field=models.CharField(default='+', max_length=255),
            preserve_default=False,
        ),
    ]
