# Generated by Django 4.1.7 on 2023-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0088_alter_reader_birthdate_alter_reader_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not set')], default='N', max_length=1),
        ),
    ]
