# Generated by Django 4.1.7 on 2023-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0090_remove_author_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='sex',
        ),
    ]
