# Generated by Django 4.1.7 on 2023-04-04 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0092_alter_reader_birthdate_alter_reader_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
