# Generated by Django 4.1.7 on 2023-04-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0093_issue_end_date_issue_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_published',
            new_name='is_posted',
        ),
    ]
