# Generated by Django 4.1.7 on 2023-04-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0094_rename_is_published_article_is_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='is_published',
            new_name='is_posted',
        ),
    ]
