# Generated by Django 4.1.7 on 2023-04-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0095_rename_is_published_issue_is_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='is_approved',
            new_name='is_posted',
        ),
    ]
