# Generated by Django 4.1.7 on 2023-04-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0096_rename_is_approved_announcement_is_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='is_approved',
            new_name='is_posted',
        ),
    ]
