# Generated by Django 4.1.7 on 2023-04-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0097_rename_is_approved_banner_is_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorposition',
            options={'verbose_name': 'Author Position', 'verbose_name_plural': 'Author Positions'},
        ),
    ]
