# Generated by Django 4.1.7 on 2023-04-04 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0098_alter_authorposition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
