# Generated by Django 4.1.7 on 2023-04-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0099_contributor_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcement',
            new_name='Update',
        ),
    ]
