# Generated by Django 4.1.7 on 2023-04-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0102_update_date_posted_update_description_update_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='article',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='publication.article'),
            preserve_default=False,
        ),
    ]
