# Generated by Django 4.1.7 on 2023-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0103_banner_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('NF', 'News Feature'), ('F', 'Feature'), ('O', 'Opinion'), ('C', 'Culture'), ('E', 'Editorial'), ('L', 'Literary')], max_length=2),
        ),
    ]
