# Generated by Django 4.1.7 on 2023-04-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0105_alter_update_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_or_headline',
            field=models.CharField(default='+', max_length=255),
            preserve_default=False,
        ),
    ]
