# Generated by Django 4.1.7 on 2023-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0106_alter_article_title_or_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date_posted',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
