# Generated by Django 4.1.7 on 2023-04-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0107_alter_update_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publication.article'),
        ),
    ]
