# Generated by Django 4.1.7 on 2023-04-18 02:45

from django.db import migrations, models
import publication.validators


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0115_alter_reader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='publication/images', validators=[publication.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
