# Generated by Django 4.1.7 on 2023-04-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0116_update_image_caption_alter_articleimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='update/images'),
        ),
    ]
