# Generated by Django 4.1.7 on 2023-04-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0117_alter_update_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publication/update/images'),
        ),
    ]
